CREATE TABLE IF NOT EXISTS users (
	id SERIAL PRIMARY KEY,
	username VARCHAR(50) UNIQUE NOT NULL,
	password_hash VARCHAR(255) NOT NULL,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS drivers (
	id SERIAL PRIMARY KEY,
	name VARCHAR(100) NOT NULL,
	vehicle VARCHAR(50) NOT NULL,
	license VARCHAR(20) UNIQUE NOT NULL,
	latitude DOUBLE PRECISION,
	longitude DOUBLE PRECISION,
	last_seen TIMESTAMP
);
